update logging functions

diff --git a/services/clang-maintenance b/services/clang-maintenance
--- a/services/clang-maintenance
+++ b/services/clang-maintenance
@@ -5,9 +5,73 @@ source_path="$prefix_path/src"
 preferred_version="${1:+llvmorg-}${1}"
 
 error()   { echo -e "\033[1;31m$*\033[0m" >&2; exit 1; }
-notice()  { echo -e "\033[1;35m$*\033[0m"; }
+notice()  { echo -e "\033[1;33m$*\033[0m"; }
 success() { echo -e "\033[1;32m$*\033[0m"; }
 code()    { echo -e "\n\t$*\n"; }
+
+window_stream() {
+    local comment="$1"
+    readonly frame_color="${WINDOW_COLOR:-5}"
+    readonly frame_height=${WINDOW_SIZE:-3}
+    local window_width
+    local window_height
+    local stream_file="/tmp/${RANDOM}.log"
+    local scrolled_lines=0
+    local reference_row
+
+    window_width=$(tput cols)
+    window_height=$(tput lines)
+
+    IFS=';' read -rsdR -p $'\E[6n' comment_row _ </dev/tty
+    comment_row=${comment_row#*[}
+
+    log "$comment"
+
+    # find a non-existing file to write the stream into
+    while [ -s "${stream_file}" ]; do stream_file="/tmp/window.${RANDOM}"; done
+
+    # capture current cursor position
+    IFS=';' read -rsdR -p $'\E[6n' reference_row _ </dev/tty
+    reference_row=${reference_row#*[}
+
+    # handle cursor jump backs in a scrolling window
+    readonly next_cursor_position=$((reference_row + frame_height))
+    readonly scrolled_lines=$((next_cursor_position - window_height))
+    if [ "${next_cursor_position}" -gt "$window_height" ]
+    then
+        # clear frame to automatically scroll the window and make the frame visible
+        printf '\033[%s;%sH' "${reference_row}" 0
+        for ((i = 0; i < frame_height; i++)); do printf "%*s\n" "${window_width}" ""; done
+        printf '\033[%s;%sH' "${reference_row}" 0
+
+        reference_row="$((reference_row - scrolled_lines))"
+    fi
+
+    while read -r line
+    do
+        # clear frame after processing previous buffer
+        printf '\033[%s;%sH' "${reference_row}" 0
+        for ((i = 0; i < frame_height; i++)); do printf "%*s\n" "${window_width}" ""; done
+        printf '\033[%s;%sH' "${reference_row}" 0
+
+        # flush buffer in the frame
+        tput bold; tput setaf "${frame_color}"
+        printf "%0.${window_width}s\n" "${line}" >> "${stream_file}"
+        tail -n "${frame_height}" "${stream_file}"
+    done
+
+    # clear frame after processing the stream
+    printf '\033[%s;%sH' "${reference_row}" 0
+    for ((i = 0; i < frame_height; i++)); do printf "%*s\n" "${window_width}" ""; done
+    printf '\033[%s;%sH' "${reference_row}" 0
+
+    # dump the file path where the stream was written into
+    printf '\033[%s;%sH' "${comment_row}" $((${#comment}+2))
+    tput bold; tput setaf 8
+    echo "${stream_file}"
+    tput sgr0; tput cnorm
+    printf '\033[%s;%sH' "${reference_row}" 0
+}
 
 [ -d "${source_path}" ] || mkdir -p "${source_path}" || error "Cannot create ${source_path}"
 
@@ -23,8 +87,7 @@ then
     git checkout main &>/dev/null
     git pull origin --prune --tags | grep '[0-9]\+ files changed, [0-9]\+ insertions(+), [0-9]\+ deletions(-)'
 else
-    notice "Cloning repository"
-    git clone https://github.com/llvm/llvm-project.git || error "Cloning failed"
+    ( git clone --progress https://github.com/llvm/llvm-project.git 2>&1 | window_stream "Cloning repository") || error "Cloning failed"
     cd llvm-project || error "${source_path}/llvm-project directory does not exist"
 fi
 
@@ -62,17 +125,11 @@ then
     fi
 fi
 
-notice "Switching to version ${required_version}"
-git checkout "${required_version}" || error "Failed to checkout to ${required_version} release tag"
-
-notice "Configuring"
-cmake -W no-dev -S llvm -B build -G 'Ninja' -D CMAKE_INSTALL_PREFIX="${prefix_path}" -D CMAKE_BUILD_TYPE=Release -D LLVM_ENABLE_PROJECTS="clang;lldb;clang-tools-extra;lld;cross-project-tests" -D LLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" -D LLVM_ENABLE_ASSERTIONS=ON -D LLVM_PARALLEL_COMPILE_JOBS=$(($(nproc) / 2 + 1)) -D LLVM_PARALLEL_LINK_JOBS=$(($(nproc) / 2 + 1)) -D LLVM_PARALLEL_TABELGEN_JOBS=$(($(nproc) / 2 + 1)) --fresh || error "Configuring failed"
-notice "Building"
-cmake --build build --parallel $(($(nproc) / 2 + 1)) --target all        || error "Building failed"
-notice "Checking"
-cmake --build build --parallel $(($(nproc) / 2 + 1)) --target check-llvm || error "Building failed"
-notice "Installing"
-cmake --install build || error "Installation failed"
+( git checkout "${required_version}" 2>&1 | window_stream "Switching to version ${required_version}") || error "Failed to checkout to ${required_version} release tag"
+( cmake -W no-dev -S llvm -B build -G 'Ninja' -D CMAKE_INSTALL_PREFIX="${prefix_path}" -D CMAKE_BUILD_TYPE=Release -D LLVM_ENABLE_PROJECTS="clang;lldb;clang-tools-extra;lld;cross-project-tests" -D LLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" -D LLVM_ENABLE_ASSERTIONS=ON -D LLVM_PARALLEL_COMPILE_JOBS=$(($(nproc) / 2 + 1)) -D LLVM_PARALLEL_LINK_JOBS=$(($(nproc) / 2 + 1)) -D LLVM_PARALLEL_TABELGEN_JOBS=$(($(nproc) / 2 + 1)) --fresh 2>&1 | window_stream "Configuring") || error "Configuring failed"
+( cmake --build build --parallel $(($(nproc) / 2 + 1)) --target all 2>&1 | window_stream "Building") || error "Building failed"
+( cmake --build build --parallel $(($(nproc) / 2 + 1)) --target check-llvm 2>&1 | window_stream "Checking") || error "Building failed"
+( cmake --install build 2>&1 | window_stream "Installing") || error "Installation failed"
 
 success "Make executables visible by updating your PATH:"
 code "include_path ${prefix_path/$HOME/\$HOME}/bin"
diff --git a/services/doxygen-maintenance b/services/doxygen-maintenance
--- a/services/doxygen-maintenance
+++ b/services/doxygen-maintenance
@@ -37,17 +37,22 @@ parse_arguments() {
 }
 
 window_stream() {
+    local comment="$1"
     readonly frame_color="${WINDOW_COLOR:-5}"
-    readonly frame_height=${WINDOW_SIZE:-5}
+    readonly frame_height=${WINDOW_SIZE:-3}
     local window_width
     local window_height
-    local stream_file
+    local stream_file="/tmp/${RANDOM}.log"
     local scrolled_lines=0
     local reference_row
 
     window_width=$(tput cols)
     window_height=$(tput lines)
-    stream_file="$(mktemp)"
+
+    IFS=';' read -rsdR -p $'\E[6n' comment_row _ </dev/tty
+    comment_row=${comment_row#*[}
+
+    log "$comment"
 
     # find a non-existing file to write the stream into
     while [ -s "${stream_file}" ]; do stream_file="/tmp/window.${RANDOM}"; done
@@ -88,11 +93,11 @@ window_stream() {
     printf '\033[%s;%sH' "${reference_row}" 0
 
     # dump the file path where the stream was written into
-    tput bold
-    tput setaf 8
-    echo -e "stored in ${stream_file}\033[0m"
-    tput cnorm
-    tput sgr0
+    printf '\033[%s;%sH' "${comment_row}" $((${#comment}+2))
+    tput bold; tput setaf 8
+    echo "${stream_file}"
+    tput sgr0; tput cnorm
+    printf '\033[%s;%sH' "${reference_row}" 0
 }
 
 prepare_source_repository() {
@@ -114,9 +119,8 @@ clean_source_repository() {
 }
 
 update_source_repository() {
-    notice "Updating repository"
     git checkout master &>/dev/null
-    git pull --prune --tags origin 2>&1 | grep '[0-9]\+ files changed, [0-9]\+ insertions(+), [0-9]\+ deletions(-)' | window_stream
+    git pull --prune --tags origin 2>&1 | grep '[0-9]\+ files changed, [0-9]\+ insertions(+), [0-9]\+ deletions(-)' | window_stream "Updating repository"
 }
 
 collect_available_versions() {
@@ -158,23 +162,19 @@ collect_current_version() {
 }
 
 change_source_repository_version() {
-    notice "Switching ${current_version:+ from }${current_version} to version ${new_version}"
-    ( git checkout "${target_version}" 2>&1 | window_stream ) || error "Failed to checkout latest version"
+    ( git checkout "${target_version}" 2>&1 | window_stream "Switching ${current_version:+ from }${current_version} to version ${new_version}") || error "Failed to checkout latest version"
 }
 
 configure_package() {
-    notice "Configuring"
-    ( cmake -S . -B "../${tool_name}-${new_version}-build" -G "Unix Makefiles" -D CMAKE_INSTALL_PREFIX="${prefix_path}" 2>&1 | window_stream ) || error "Configuring failed"
+    ( cmake -S . -B "../${tool_name}-${new_version}-build" -G "Unix Makefiles" -D CMAKE_INSTALL_PREFIX="${prefix_path}" 2>&1 | window_stream "Configuring") || error "Configuring failed"
 }
 
 build_project() {
-    notice "Building"
-    ( cmake --build "../${tool_name}-${new_version}-build" --parallel $(($(nproc) / 2)) 2>&1 | window_stream ) || error "Building failed"
+    ( cmake --build "../${tool_name}-${new_version}-build" --parallel $(($(nproc) / 2)) 2>&1 | window_stream "Building") || error "Building failed"
 }
 
 install_artifacts() {
-    notice "Installing"
-    ( cmake --install "../${tool_name}-${new_version}-build" 2>&1 | window_stream ) || error "Installation failed"
+    ( cmake --install "../${tool_name}-${new_version}-build" 2>&1 | window_stream "Installing") || error "Installation failed"
 }
 
 notify_path() {
diff --git a/services/ninja-maintenance b/services/ninja-maintenance
--- a/services/ninja-maintenance
+++ b/services/ninja-maintenance
@@ -10,9 +10,73 @@ distro="$(awk '{FS="="} $1=="ID" {print $2}' /etc/os-release | tr -d '"')"
 release="$(awk '{FS="="} $1=="VERSION_ID" {print $2}' /etc/os-release | tr -d '"')"
 
 error()   { echo -e "\033[1;31m$*\033[0m" >&2; exit 1; }
-notice()  { echo -e "\033[1;35m$*\033[0m"; }
+notice()  { echo -e "\033[1;33m$*\033[0m"; }
 success() { echo -e "\033[1;32m$*\033[0m"; }
 code()    { echo -e "\n\t$*\n"; }
+
+window_stream() {
+    local comment="$1"
+    readonly frame_color="${WINDOW_COLOR:-5}"
+    readonly frame_height=${WINDOW_SIZE:-3}
+    local window_width
+    local window_height
+    local stream_file="/tmp/${RANDOM}.log"
+    local scrolled_lines=0
+    local reference_row
+
+    window_width=$(tput cols)
+    window_height=$(tput lines)
+
+    IFS=';' read -rsdR -p $'\E[6n' comment_row _ </dev/tty
+    comment_row=${comment_row#*[}
+
+    log "$comment"
+
+    # find a non-existing file to write the stream into
+    while [ -s "${stream_file}" ]; do stream_file="/tmp/window.${RANDOM}"; done
+
+    # capture current cursor position
+    IFS=';' read -rsdR -p $'\E[6n' reference_row _ </dev/tty
+    reference_row=${reference_row#*[}
+
+    # handle cursor jump backs in a scrolling window
+    readonly next_cursor_position=$((reference_row + frame_height))
+    readonly scrolled_lines=$((next_cursor_position - window_height))
+    if [ "${next_cursor_position}" -gt "$window_height" ]
+    then
+        # clear frame to automatically scroll the window and make the frame visible
+        printf '\033[%s;%sH' "${reference_row}" 0
+        for ((i = 0; i < frame_height; i++)); do printf "%*s\n" "${window_width}" ""; done
+        printf '\033[%s;%sH' "${reference_row}" 0
+
+        reference_row="$((reference_row - scrolled_lines))"
+    fi
+
+    while read -r line
+    do
+        # clear frame after processing previous buffer
+        printf '\033[%s;%sH' "${reference_row}" 0
+        for ((i = 0; i < frame_height; i++)); do printf "%*s\n" "${window_width}" ""; done
+        printf '\033[%s;%sH' "${reference_row}" 0
+
+        # flush buffer in the frame
+        tput bold; tput setaf "${frame_color}"
+        printf "%0.${window_width}s\n" "${line}" >> "${stream_file}"
+        tail -n "${frame_height}" "${stream_file}"
+    done
+
+    # clear frame after processing the stream
+    printf '\033[%s;%sH' "${reference_row}" 0
+    for ((i = 0; i < frame_height; i++)); do printf "%*s\n" "${window_width}" ""; done
+    printf '\033[%s;%sH' "${reference_row}" 0
+
+    # dump the file path where the stream was written into
+    printf '\033[%s;%sH' "${comment_row}" $((${#comment}+2))
+    tput bold; tput setaf 8
+    echo "${stream_file}"
+    tput sgr0; tput cnorm
+    printf '\033[%s;%sH' "${reference_row}" 0
+}
 
 [ -d ${source_path} ] || mkdir -p ${source_path} || error "Cannot create ${source_path}"
 
@@ -29,7 +93,7 @@ then
     git pull --prune --tags origin | grep '[0-9]\+ files changed, [0-9]\+ insertions(+), [0-9]\+ deletions(-)'
 else
     notice "Cloning repository"
-    git clone https://github.com/ninja-build/ninja.git || error "Cloning failed"
+    ( git clone --progress https://github.com/ninja-build/ninja.git 2>&1 | window_stream ) || error "Cloning failed"
     cd ninja || error "${source_path}/ninja directory does not exist"
 fi
 
@@ -52,16 +116,12 @@ then
     fi
 fi
 
-notice "Switch version${current_version:+ from }${current_version} to ${latest_version}"
-git checkout "${latest_version}" || error "Failed to checkout latest version"
-notice "Bootstraping"
-./bootstrap --prefix="${prefix_path}" || error "Bootstraping failed"
-notice "Configuring"
-./configure --prefix="${prefix_path}" || error "Configuring failed"
-notice "Building"
-make -j$(($(nproc) / 2 + 1)) || error "Building failed"
-notice "Installing"
-make install || error "Installation failed"
+
+( git checkout "${latest_version}" 2>&1 | window_stream "Switch version${current_version:+ from }${current_version} to ${latest_version}" ) || error "Failed to checkout latest version"
+( ./bootstrap --prefix="${prefix_path}" 2>&1 | widnow_stream "Bootstraping" ) || error "Bootstraping failed"
+( ./configure --prefix="${prefix_path}" 2>&1 | window_stream "Configuring" ) || error "Configuring failed"
+( make -j$(($(nproc) / 2 + 1)) 2>&1 | window_stream "Building" ) || error "Building failed"
+( make install 2>&1 | window_stream "Installing") || error "Installation failed"
 
 success "Make executables visible by updating your PATH:"
 code "include_path ${prefix_path/$HOME/\$HOME}/.local/bin"
diff --git a/services/node-maintenance b/services/node-maintenance
--- a/services/node-maintenance
+++ b/services/node-maintenance
@@ -1,9 +1,73 @@
 #!/usr/bin/env bash
 
 error()   { echo -e "\033[1;31m$*\033[0m" >&2; exit 1; }
-notice()  { echo -e "\033[1;35m$*\033[0m"; }
+notice()  { echo -e "\033[1;33m$*\033[0m"; }
 success() { echo -e "\033[1;32m$*\033[0m"; }
 code()    { echo -e "\n\t$*\n"; }
+
+window_stream() {
+    local comment="$1"
+    readonly frame_color="${WINDOW_COLOR:-5}"
+    readonly frame_height=${WINDOW_SIZE:-3}
+    local window_width
+    local window_height
+    local stream_file="/tmp/${RANDOM}.log"
+    local scrolled_lines=0
+    local reference_row
+
+    window_width=$(tput cols)
+    window_height=$(tput lines)
+
+    IFS=';' read -rsdR -p $'\E[6n' comment_row _ </dev/tty
+    comment_row=${comment_row#*[}
+
+    log "$comment"
+
+    # find a non-existing file to write the stream into
+    while [ -s "${stream_file}" ]; do stream_file="/tmp/window.${RANDOM}"; done
+
+    # capture current cursor position
+    IFS=';' read -rsdR -p $'\E[6n' reference_row _ </dev/tty
+    reference_row=${reference_row#*[}
+
+    # handle cursor jump backs in a scrolling window
+    readonly next_cursor_position=$((reference_row + frame_height))
+    readonly scrolled_lines=$((next_cursor_position - window_height))
+    if [ "${next_cursor_position}" -gt "$window_height" ]
+    then
+        # clear frame to automatically scroll the window and make the frame visible
+        printf '\033[%s;%sH' "${reference_row}" 0
+        for ((i = 0; i < frame_height; i++)); do printf "%*s\n" "${window_width}" ""; done
+        printf '\033[%s;%sH' "${reference_row}" 0
+
+        reference_row="$((reference_row - scrolled_lines))"
+    fi
+
+    while read -r line
+    do
+        # clear frame after processing previous buffer
+        printf '\033[%s;%sH' "${reference_row}" 0
+        for ((i = 0; i < frame_height; i++)); do printf "%*s\n" "${window_width}" ""; done
+        printf '\033[%s;%sH' "${reference_row}" 0
+
+        # flush buffer in the frame
+        tput bold; tput setaf "${frame_color}"
+        printf "%0.${window_width}s\n" "${line}" >> "${stream_file}"
+        tail -n "${frame_height}" "${stream_file}"
+    done
+
+    # clear frame after processing the stream
+    printf '\033[%s;%sH' "${reference_row}" 0
+    for ((i = 0; i < frame_height; i++)); do printf "%*s\n" "${window_width}" ""; done
+    printf '\033[%s;%sH' "${reference_row}" 0
+
+    # dump the file path where the stream was written into
+    printf '\033[%s;%sH' "${comment_row}" $((${#comment}+2))
+    tput bold; tput setaf 8
+    echo "${stream_file}"
+    tput sgr0; tput cnorm
+    printf '\033[%s;%sH' "${reference_row}" 0
+}
 
 export NVM_DIR="$HOME/.nvm"
 
@@ -12,15 +76,15 @@ then
     [ -h "$NVM_DIR/nvm.sh" ] && [ ! -s "$NVM_DIR/nvm.sh" ] && unlink "$NVM_DIR/nvm.sh"
     (
         cd "$NVM_DIR"
-        git fetch --tags origin
-        git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
+        ( git fetch --tags origin 2>&1 | window_stream "Updating repository" )
+        ( git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)` 2>&1 | window_stream "Switching branch" )
     ) && \. "$NVM_DIR/nvm.sh"
 else
     [ -d "$NVM_DIR" ] && rm -r "$NVM_DIR"
     (
-        git clone https://github.com/nvm-sh/nvm.git "$NVM_DIR"
+        ( git clone --progress https://github.com/nvm-sh/nvm.git "$NVM_DIR" 2>&1 | window_stream "Cloning repository" )
         cd "$NVM_DIR"
-        git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
+        ( git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)` 2>&1 | window_stream "Switching branch" )
     ) && \. "$NVM_DIR/nvm.sh" && success "nvm installed"
 fi
 
@@ -34,8 +98,8 @@ then
     success "$(basename "${0%%-*}") already on latest version" && exit 0
 fi
 
-nvm install-latest-npm || error "Failed to install latest npm"
-nvm install "${latest_version}" || error "Failed to install latest node version ${latest_version}"
-nvm use "${latest_version}" || error "Failed to switch node to version ${latest_version}"
-nvm alias default "${latest_version}" || error "Failed to set new version ${latest_version} as default"
-nvm uninstall "${current_version}" || error "Failed to uninstall previous version ${current_version}"
+( nvm install-latest-npm 2>&1 | window_stream "Updating npm" ) || error "Failed to install latest npm"
+( nvm install "${latest_version}" 2>&1 | window_stream "Installing node" ) || error "Failed to install latest node version ${latest_version}"
+( nvm use "${latest_version}" 2>&1 | window_stream "Setting default version" ) || error "Failed to switch node to version ${latest_version}"
+( nvm alias default "${latest_version}" 2>&1 | window_stream "Creating alias" ) || error "Failed to set new version ${latest_version} as default"
+( nvm uninstall "${current_version}" 2>&1 | window_stream "Uninstalling previous version" ) || error "Failed to uninstall previous version ${current_version}"
