implement doxygen maintenance service

diff --git a/services/gcc-maintenance b/services/gcc-maintenance
--- a/services/gcc-maintenance
+++ b/services/gcc-maintenance
@@ -3,72 +3,67 @@
 prefix_path="${PREFIX_PATH:-$HOME/.local}"
 source_path="$prefix_path/src"
 preferred_version="${1}"
-
-machine="$(uname -m)"
-os="$(uname -s)"
-os="${os,,}"
-distro="$(awk '{FS="="} $1=="ID" {print $2}' /etc/os-release | tr -d '"')"
-release="$(awk '{FS="="} $1=="VERSION_ID" {print $2}' /etc/os-release | tr -d '"')"
+unset LDFLAGS
+unset CXXFLAGS
+unset CPPFLAGS
 
 error()   { echo -e "\033[1;31m$*\033[0m" >&2; exit 1; }
 notice()  { echo -e "\033[1;35m$*\033[0m"; }
 success() { echo -e "\033[1;32m$*\033[0m"; }
 code()    { echo -e "\n\t$*\n"; }
 
-[ -d ${source_path} ] || mkdir -p ${source_path} || error "Cannot create ${source_path}"
+mkdir --parents "${source_path}"
+cd "${source_path}" || error "Cannot move to ${source_path}"
 
-cd ${source_path} || error "Cannot move to ${source_path}"
-
-if [ -d ${source_path}/gcc ]
+if ! [ -d gcc ]
 then
-    notice "Cleaning repository"
-    cd gcc || error "Failed to move into ${source_path}/gcc directory"
-    git status | sed -n '/^Untracked files:$/,/^$/{1,3d;p}' | xargs rm -rf
-
-    notice "Updating repository"
-    git checkout master &>/dev/null
-    git pull --prune --tags origin | grep '[0-9]\+ files changed, [0-9]\+ insertions(+), [0-9]\+ deletions(-)'
-else
     notice "Cloning repository"
     git clone git://gcc.gnu.org/git/gcc.git || error "Cloning failed"
-    cd gcc || error "${source_path}/gcc directory does not exist"
 fi
 
-# all available versions
+cd gcc || error "Failed to move into ${source_path}/gcc directory"
+
+notice "Cleaning repository"
+git status | sed -n '/^Untracked files:$/,/^$/{1,3d;p}' | xargs rm -rf
+
+notice "Updating repository"
+git checkout master &>/dev/null
+git pull --prune --tags origin | grep '[0-9]\+ files changed, [0-9]\+ insertions(+), [0-9]\+ deletions(-)'
+
 notice "Fetching version list"
-read -a versions <<< $(git tag --sort version:refname | grep -E 'v[0-9.]+$' | tac | xargs)
+read -ra versions <<< "$(git tag --sort version:refname | grep -E '^releases/gcc-[0-9.]+$' | tac | xargs)"
+
+current_version=
+target_version="${versions[0]}"
 
 if [ -n "$preferred_version" ]
 then
-    if grep -q "$preffered_version" <<< "${versions[*]}"
+    if grep -q "$preferred_version" <<< "${versions[*]}"
     then
-        latest_version="$preferred_version"
+        target_version="releases/gcc-$preferred_version"
     fi
 fi
 
-index=0
-current_version=
-latest_version="${versions[$index]}"
-
 if [ -x "${prefix_path}/bin/gcc" ]
 then
-    current_version="v$(${prefix_path}/bin/gcc --version | sed -En 's/.*[^0-9](([0-9]+\.){2}[0-9]+).*/\1/p;q')"
+    current_version="releases/gcc-$("${prefix_path}/bin/gcc" --version | sed -En 's/.*[^0-9](([0-9]+\.){2}[0-9]+).*/\1/p;q')"
 
-    if [ "${current_version}" == "${latest_version}" ]
+    if [ "${current_version}" == "${target_version}" ]
     then
-        success "$(basename "${0%%-*}") already using latest version ${latest_version}"
+        success "$(basename "${0%%-*}") already using latest version ${target_version#*-}"
         exit 0
     fi
 fi
 
-notice "Switch version${current_version:+ from }${current_version} to ${latest_version}"
-git checkout "${latest_version}" || error "Failed to checkout latest version"
-notice "Bootstraping"
-./bootstrap --prefix="${prefix_path}" || error "Bootstraping failed"
+notice "Switching version${current_version:+ from }${current_version#*-} to ${target_version#*-}"
+git checkout "${target_version}" || error "Failed to checkout latest version"
+
 notice "Configuring"
-./configure --prefix="${prefix_path}" || error "Configuring failed"
+./configure --prefix="${prefix_path}" --disable-multilib || error "Configuring failed"
+
 notice "Building"
 make -j$(($(nproc) / 2 + 1)) || error "Building failed"
+
 notice "Installing"
 make install || error "Installation failed"
 
