node-maintainer: add error conditions

diff --git a/services/node-maintenance b/services/node-maintenance
--- a/services/node-maintenance
+++ b/services/node-maintenance
@@ -1,9 +1,10 @@
 #!/usr/bin/env bash
 
+error() { tput setaf 1; tput bold; echo "$@" >&2; tput sgr0; exit 1; }
+
 if [ ! -d "$HOME/.nvm" ] || [ ! -s "$HOME/.nvm/nvm.sh" ]
 then
-    echo "nvm not installed" >&2
-    exit 1
+    error "nvm not installed"
 fi
 
 source "$HOME/.nvm/nvm.sh"
@@ -11,10 +12,13 @@ source "$HOME/.nvm/nvm.sh"
 current_version="$(nvm version)"
 latest_version="$(nvm version-remote)"
 
-if [ "${current_version}" != "${latest_version}" ]
+if [ "${current_version}" == "${latest_version}" ]
 then
-    nvm install-latest-npm
-    nvm install "${latest_version}"
+    error "Already on latest version"
 fi
 
-nvm use "${latest_version}"
+nvm install-latest-npm || error "Failed to install latest npm"
+nvm install "${latest_version}" || error "Failed to install latest node version ${latest_version}"
+nvm use "${latest_version}" || error "Failed to switch node to version ${latest_version}"
+nvm alias default "${latest_version}" || error "Failed to set new version ${latest_version} as default"
+nvm uninstall "${current_version}" || error "Failed to uninstall previous version ${current_version}"
