add logging to mtproto

diff --git a/scripts/mtproto b/scripts/mtproto
--- a/scripts/mtproto
+++ b/scripts/mtproto
@@ -1,74 +1,118 @@
 #!/usr/bin/env bash
 
-country="US"
+mtproto_country="US"
+mtproto_cache="/tmp/mtproto.hosts"
 
-function get_help() {
+function mtproto_usage() {
     echo "mtproto [-h] [-c <country_name=US>]"
     echo
     echo "options"
     echo
     echo " -h,--help            print help menu"
     echo " -c,--country <code>  country code or name"
-    exit
+    echo " -l,--limit <numbers> number of matches"
 }
 
-function choose_country() {
+function mtproto_choose_country() {
     local country_name="$1"
 
     case "${country_name,,}" in
-        gb|britain) country=GB ;;
-        us|america) country=US ;;
-        de|germany) country=DE ;;
-        *) echo "unknown country, falling back to US"; country=US
+        gb|britain) mtproto_country=GB ;;
+        us|america) mtproto_country=US ;;
+        de|germany) mtproto_country=DE ;;
+        *) echo "unknown country, falling back to US"; mtproto_country=US
     esac
 }
 
 function mtproto() {
-    [ -s /tmp/mtproto.hosts ] && rm /tmp/mtproto.hosts
+    local match_limit=1
+    local max_count="$match_limit"
+    local address_list="/tmp/mtproto.list"
+    local index
+    local country
+    local country
+    local port
+    local host
+    local secret
+    local object
+    local latency
+    local address
+    local entries
+    local accepted=0
+    local ping_entry
+    local query
+
+    [ -s "$mtproto_cache" ] && rm "$mtproto_cache"
 
     while [ $# -gt 0 ]
     do
         case "$1" in
-            -h|--help) get_help ;;
-            -c|--country) choose_country "$2"; limit_country=1; shift ;;
-            *) get_help ;;
+            -h|--help) mtproto_usage; return ;;
+            -c|--country) mtproto_choose_country "$2"; shift ;;
+            -l|--limit) match_limit="$2"; shift ;;
+            *) mtproto_usage; return ;;
         esac
         shift
     done
 
+    case "$match_limit" in
+        [0-9]*) max_count="$match_limit" ;;
+        *) match_limit=1; max_count="1" ;;
+    esac
+
     # retrieve latest proxy list
-    curl -s 'https://mtpro.xyz/api/?type=mtproto' > /tmp/mtproto.list
+    if ! curl -s 'https://mtpro.xyz/api/?type=mtproto' > "$address_list"
+    then
+        echo "failed to load uri" >&2
+        return
+    fi
 
-    max_count=4
+    entries="$(jq '. | length' "$address_list")"
+    query="$accepted ($index/$entries)"
 
-    for mt_index in $(seq 0 "$(jq '. | length' /tmp/mtproto.list)")
+    echo -n "loading entry $query" >&2
+
+    for index in $(seq 0 "${entries:-1}")
     do
-        mt_object="$(jq -r ".[$mt_index]" /tmp/mtproto.list)"
-        mt_country="$(jq -r '.country' <<< "$mt_object")"
+        printf "%0.s\b" $(seq 1 "${#query}") >&2
 
-        if [ "${limit_country:-0}" -eq 1 ] && [ "$mt_country" != "$country" ]
+        query="$accepted ($index/$entries)"
+        echo -ne "$query" >&2
+
+        object="$(jq -r ".[$index]" "$address_list")"
+        country="$(jq -r '.country' <<< "$object")"
+
+        if [ "$country" != "$mtproto_country" ]
         then
             continue
         fi
 
-        mt_host="$(jq -r '.host' <<< "$mt_object")"
-        mt_port="$(jq -r '.port' <<< "$mt_object")"
-        mt_secret="$(jq -r '.secret' <<< "$mt_object")"
+        host="$(jq -r '.host' <<< "$object")"
+        port="$(jq -r '.port' <<< "$object")"
+        secret="$(jq -r '.secret' <<< "$object")"
 
-        if ping -n -c 1 -W 1 "$mt_host" | awk -v cc="$mt_country" -v host="$mt_host" -v port="$mt_port" -v secret="$mt_secret" 'BEGIN{FS="/"} $1 == "rtt min" {printf "%d %s tg://proxy?server=%s&port=%d&secret=%s\n", $5,cc,host,port,secret}' >> /tmp/mtproto.hosts
+        if ping_entry="$(ping -n -c1 -W1 "$host")"
         then
-            ((--max_count))
+            echo "$ping_entry" | awk -v c="$country" \
+             -v h="$host" \
+             -v p="$port" \
+             -v s="$secret" \
+             'BEGIN{FS="/"} $1 == "rtt min" {printf "%d %s tg://proxy?server=%s&port=%d&secret=%s\n", $5,c,h,p,s}'
 
-            [ "$max_count" -eq 0 ] && break
+            ((++accepted))
+            [ "$((--max_count))" -eq 0 ] && break
         fi
 
-        ((++mt_index))
+        ((++index))
+    done | nl | sort -k 2 -n 1> "$mtproto_cache"
+    echo; echo
+
+    for index in $(seq 1 "$match_limit")
+    do
+        latency="$(sed -n "${index}p" "$mtproto_cache" | awk '{print $2}')"
+        country="$(sed -n "${index}p" "$mtproto_cache" | awk '{print $3}')"
+        address="$(sed -n "${index}p" "$mtproto_cache" | awk '{print $4}')"
+
+        echo -e "\e[1;31m""${latency}ms: ""\e[0m""$address"
     done
-
-    mt_line="$(nl /tmp/mtproto.hosts | sort -k 2 -n | head -n 1 | awk '{print $1}')"
-    mt_ping="$(sed -n "${mt_line}p" /tmp/mtproto.hosts | cut -d ' ' -f 1)"
-    mt_country="$(sed -n "${mt_line}p" /tmp/mtproto.hosts | cut -d ' ' -f 2)"
-    mt_address="$(sed -n "${mt_line}p" /tmp/mtproto.hosts | cut -d ' ' -f 3)"
-
-    echo -e "\e[1;31m""$mt_ping ms ($mt_country): ""\e[0m""$mt_address"
 }
